package com.github.griga23;

import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.errors.SerializationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

import java.io.IOException;
import java.util.Properties;

public class KafkaAvroProducerCCloudDemo {

    private static Logger logger = LoggerFactory.getLogger(KafkaAvroProducerCCloudDemo.class);

    public static void main(String[] args) throws IOException {

        if (args.length < 1) {
            throw new IllegalArgumentException(
                    "Please provide: the path to an environment configuration file");
        }

        // initialize Kafka producer
        final Properties props = loadProperties(args[0]);
        final Producer<String, Customer> producer = new KafkaProducer<>(props);
        final String topic = props.getProperty("customer.topic.name");

        //JSON parser object to parse read file
        JSONParser jsonParser = new JSONParser();

        // create Customer object
        // Customer object must be already generated by the maven plugin
        Customer customer = new Customer();

        try (FileReader reader = new FileReader("customerEvent.json"))
        {
            //Read JSON file
             Object obj = jsonParser.parse(reader);
            JSONObject customerJSON = (JSONObject) obj;

            customer = Customer.newBuilder()
                    .setAge((long)customerJSON.get("age"))
                    .setAutomatedEmail((boolean)customerJSON.get("automated_email"))
                    .setFirstName((String)customerJSON.get("first_name"))
                    .setLastName((String)customerJSON.get("last_name"))
                    .setHeight((double)customerJSON.get("height"))
                    .setWeight((double)customerJSON.get("weight"))
                    .build();

        } catch (IOException | ParseException e) {
            e.printStackTrace();
        }

        // serialize single Kafka ProducerRecord based on the Customer object
        ProducerRecord<String, Customer> producerRecord =
                new ProducerRecord<String, Customer>(topic, customer.getLastName(), customer);
        logger.info("Customer ProducerRecord created: " + customer.toString());

        // send ProducerRecord to Kafka Broker in CCloud
        try{
            producer.send(producerRecord);
            logger.info("ProducerRecord sent successfully to Kafka!");
        }catch (SerializationException e){
            logger.warn(e.getCause().getMessage());
            logger.warn("ProducerRecord sent to DLQ!");
//            e.printStackTrace();
        }
        finally {
            producer.flush();
            producer.close();
        }
    }


    // load properties from some file
    public static Properties loadProperties(String fileName) throws IOException {
        final Properties envProps = new Properties();
        final FileInputStream input = new FileInputStream(fileName);
        envProps.load(input);
        input.close();

        return envProps;
    }
}
